---
name: ada_topics
channels: [conda-forge, nodefaults]
dependencies:
  - deepdiff
  - gitpython
  - ipykernel
  - ipywidgets
  - jupyterlab
  - nodejs
  - numba
  - openpyxl
  - pandas >= 2.2
  - pdbpp
  - pip
  - plotly
  - pre-commit
  - pyarrow
  - pybaum
  - pydata-sphinx-theme>=0.13.3
  - pygraphviz
  - pytask
  # - pytask-parallel  # Do not use, slidev exports get mixed up.
  - pytest
  - pytest-cov
  - pytest-xdist
  - python==3.12
  - pyyaml
  - scikit-learn
  - setuptools_scm
  - snakeviz
  - sphinx
  - sphinx-automodapi
  - sphinx-copybutton
  - sphinxcontrib-mermaid
  - statsmodels
  - toml
  - xlrd>=1.0
  - pip: [-e ., kaleido, jupyter-book, pyperclip]
